### ISSUE TITLE
Session store api name is? ha8Ns0Kab2

### ISSUE THREAD

**Issue by inrl-official** [TOXIC-DEVIL/Leon#8]

**Comment by inrl-official** [comment]
> > _No description provided._
> 
> What you mean ? That question doesn't make any sense.

dev!please encrypt your auth_id, for deployment we share my key to anyone thet take our creds.json file and may copy our whatsapp data

**Comment by TOXIC-DEVIL** [comment]
> > > _No description provided._
> > 
> > 
> > What you mean ? That question doesn't make any sense.
> 
> dev!please encrypt your auth_id, for deployment we share my key to anyone thet take our creds.json file and may copy our whatsapp data

Using apis like pastebin etc.. are not safer, developer can access it. I accept your concern, I am looking for a safer way to encrypt it and will be updated here soon. This is for temporary and I don't wanna access my users account. If you are concerned about security, You can install bot later as I will report here when I find a safer way.

**Comment by TOXIC-DEVIL** [comment]
> > > _No description provided._
> > 
> > 
> > What you mean ? That question doesn't make any sense.
> 
> dev!please encrypt your auth_id, for deployment we share my key to anyone thet take our creds.json file and may copy our whatsapp data

Sorry, I just misunderstood your concern for a while. As you said, encrypting authentication id is not completely safe. If a developer even encrypt it, They can decrypt it also. Like.. for example, If I encrypt users authentication code and then when I want to read the authentication code, I should decode it for that if I'm using any external source of storage for auth id. You can use Leon without any concern.

**Comment by TOXIC-DEVIL** [comment]
> > > _No description provided._
> > 
> > 
> > What you mean ? That question doesn't make any sense.
> 
> dev!please encrypt your auth_id, for deployment we share my key to anyone thet take our creds.json file and may copy our whatsapp data

I understand your concern, What you mean is not completely right. And you claimed that anyone can use your auth_id, but the place where it is stored is not publicly shown as the code is encrypted and users can't access it. But your concern may include 'developer can access it' yes, I can but why should I do it coz I don't want to access someone's account for no reason. Also i am not able to identify auth for of someone's specifically. Due to your concern, I can update authentication system in which I can't access auth_id.
